config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :coins

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  layout 'test'

  before_action :set_coin, only: [:show, :edit, :update, :destroy]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Coin was successfully created.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Coin was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Coin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user_name = params[:name] ? params[:name] : 'User'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_br date_us
    date_us.strftime('%d/%m/%Y')
  end

  def env_rails
    if Rails.env.production?
      'Prod'
    elsif Rails.env.development?
      'Dev'
    else
      'Testing...'
    end
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
    <%= image_tag coin.url_image, size: '25x25' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coins</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th>Url image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, width: 25,  height: 25 %></td>
        <td><%= link_to 'Show', coin %></td>
        <td><%= link_to 'Edit', edit_coin_path(coin) %></td>
        <td><%= link_to 'Destroy', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coin', new_coin_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url image:</strong>
  <%= image_tag @coin.url_image, width: 25,  height: 25 %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><p>Today is <%= date_br(Date.today) %></p></header>
    <%= yield %>
    <footer>CryptoWallet - 2020</footer>
  </body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><p>Header Coins</p></header>
    <%= yield %>
    <footer>Footer Coins - 2020</footer>
  </body>
</html>

app/views/welcome/_menu.html.erb
<ul>
  <li>
    <%= link_to 'Welcome', welcome_index_path %>
  </li>
  <li>
    <%= link_to 'Coins', coins_path %>
  </li>
</ul>

app/views/welcome/index.html.erb
<h1>Welcome, <%= @user_name %></h1>
<p>ENV: <%= env_rails %> </p>

<%= render 'menu' %>